#Permet de faire les regroupements de variables
source("./Code regroupement/Regroupement Enfant Total.R")
source("./Code regroupement/Regroupement Enfant ACC.R")
source("./Code regroupement/Regroupement Enfant Non ACC.R")
source("./Code regroupement/Regroupement PA Total.R")
source("./Code regroupement/Regroupement PA ACC.R")
source("./Code regroupement/Regroupement PA Non ACC.R")
source("./Code regroupement/Regroupement Adultes Total.R")
source("./Code regroupement/Regroupement Adultes ACC.R")
source("./Code regroupement/Regroupement Adultes Non ACC.R")